catList = ['Active Directory',
 'Adobe',
 'Adobe Acrobat/Reader',
 'Adobe AIR',
 'Adobe ColdFusion',
 'Adobe Digital Editions',
 'Adobe Flash',
 'Adobe Shockwave',
 'Alpine Linux',
 'Amazon',
 'Amazon Linux AMI',
 'Anti-virus',
 'Apache',
 'Apache HTTP Server',
 'Apache Struts',
 'Apache Tomcat',
 'APC',
 'Apple',
 'Apple iOS',
 'Apple iTunes',
 'Apple Java',
 'Apple Mac OS X',
 'Apple QuickTime',
 'Apple Safari',
 'Atlassian',
 'Atlassian JIRA',
 'Backdoor',
 'Backup',
 'Beanbag Review Board',
 'Browsers',
 'Canonical',
 'CentOS',
 'CGI',
 'Check Point',
 'Check Point Firewall',
 'CIFS',
 'Cisco',
 'Cisco ASA',
 'Cisco AsyncOS',
 'Cisco IOS',
 'Cisco IronPort',
 'Cisco NX',
 'Cisco PIX',
 'Cisco SAN',
 'Cisco TelePresence',
 'Cisco UCS',
 'Citect',
 'Citrix',
 'Citrix XenDesktop',
 'Conexant Systems',
 'CSRF',
 'Custom Web Application',
 'CVS',
 'Database',
 'DCE/RPC',
 'Debian Linux',
 'Default Account',
 'Denial of Service',
 'DHCP',
 'Directory Browsing',
 'Directory Traversal',
 'DNS',
 'Dnsmasq',
 'Docker',
 'Drupal',
 'EulerOS',
 'Exim',
 'F5',
 'F5 BIG-IP',
 'Fedora',
 'Fedora Core Linux',
 'FFmpeg',
 'Finger',
 'Fortinet',
 'Fortinet FortiAnalyzer',
 'Fortinet FortiGate',
 'Fortinet FortiManager',
 'Fortinet FortiOS',
 'FreeBSD',
 'FTP',
 'Game',
 'General Remote Services',
 'Gentoo Linux',
 'Google',
 'Google Android',
 'Google Chrome',
 'HP',
 'HP Data Protector',
 'HP iLO',
 'HP System Management Homepage',
 'HP Systems Insight Manager',
 'HTTP',
 'HTTP Response Splitting',
 'Huawei',
 'IAVM',
 'IBM',
 'IBM AIX',
 'IBM AS/400',
 'IBM DB2',
 'IBM Lotus Notes/Domino',
 'IMail',
 'IMAP',
 'Information Gathering',
 'Insecure Remote Access',
 'Intel',
 'Intel AMT',
 'IPMI',
 'IPSEC',
 'ISC',
 'ISC BIND',
 'J2EE',
 'Jenkins',
 'Joomla!',
 'jQuery',
 'Juniper',
 'Juniper Junos OS',
 'Juniper ScreenOS',
 'LDAP',
 'lighttpd',
 'Linux',
 'Mail',
 'MediaWiki',
 'Microsoft',
 'Microsoft .NET Framework',
 'Microsoft ASP',
 'Microsoft ASP.NET',
 'Microsoft Exchange',
 'Microsoft IIS',
 'Microsoft Internet Explorer',
 'Microsoft MSXML',
 'Microsoft Office',
 'Microsoft Office for Mac',
 'Microsoft Outlook',
 'Microsoft Patch',
 'Microsoft SharePoint',
 'Microsoft Silverlight',
 'Microsoft SQL Server',
 'Microsoft Windows',
 'Mobile',
 'MongoDB',
 'Moodle',
 'Mozilla',
 'Mozilla Bugzilla',
 'Mozilla Firefox',
 'Mozilla SeaMonkey',
 'Mozilla Thunderbird',
 'NAT',
 'NDMP',
 'NetWare',
 'Network',
 'News',
 'NFS',
 'Nginx',
 'NTP',
 'Obsolete OS',
 'Obsolete Software',
 'OpenSSH',
 'OpenSSL',
 'Oracle',
 'Oracle Database',
 'Oracle iPlanet',
 'Oracle Java',
 'Oracle Linux',
 'Oracle MySQL',
 'Oracle Solaris',
 'Oracle WebLogic',
 'OWASP_2010',
 'OWASP_2013',
 'Palo Alto Networks',
 'PAN',
 'pfSense',
 'PHP',
 'PHPMyAdmin',
 'Point of Sale',
 'Policy Violation',
 'POP',
 'Postfix',
 'PostgreSQL',
 'PPTP',
 'Privilege Escalation',
 'Proxy',
 'Rapid7 Critical',
 'RealNetworks',
 'RealNetworks Helix',
 'Red Hat',
 'Red Hat Enterprise Linux',
 'Red Hat JBoss',
 'Remote Execution',
 'Remote Shell',
 'RPC',
 'rsync',
 'Ruby on Rails',
 'Samba',
 'SCADA',
 'Sendmail',
 'SMTP',
 'SNMP',
 'Spyware',
 'SQL Injection',
 'Squid',
 'SSH',
 'SuSE',
 'Symantec',
 'Symantec Endpoint Protection',
 'Symantec Endpoint Protection Manager',
 'Symantec pcAnywhere',
 'Symantec Scan Engine',
 'TDS',
 'Telnet',
 'TFTP',
 'Trojan',
 'Ubuntu Linux',
 'UNIX',
 'UPnP',
 'VideoLAN',
 'VideoLAN VLC',
 'Virus',
 'VMware',
 'VMware ESX/ESXi',
 'VMware Fusion',
 'VMware Player',
 'VMware Workstation',
 'VPN',
 'Web',
 'Web Spider',
 'Wireless',
 'Wireshark',
 'WordPress',
 'Worm',
 'X Window System',
 'XnSoft',
 'XnSoft XnView',
 'XSS',
 'Zone Transfer']

importantPorts = ["port_443", 
                  "port_80", 
                  "port_8080", 
                  "port_3306", 
                  "port_8000", 
                  "port_135", 
                  "port_22", 
                  "port_21", 
                  "port_139", 
                  "port_110",
                  "port_25", 
                  "port_53", 
                  "port_3389", 
                  "port_23", 
                  "port_161", 
                  "port_8443", 
                  "port_5000", 
                  "port_1337", 
                  "port_123", 
                  "port_162", 
                  "port_5432", 
                  "port_9443"]